/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

/**
 *
 * @author luisf
 */
public class jtfEditService extends javax.swing.JInternalFrame {

    /**
     * Creates new form jtfEditService
     */
    public jtfEditService() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlbTitulo = new javax.swing.JLabel();
        jrbMantCorrectivo = new javax.swing.JRadioButton();
        jbnVolver = new javax.swing.JButton();
        jlbDescripcionServicio = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaDescripcionServicio = new javax.swing.JTextArea();
        jlbPrecioServicio = new javax.swing.JLabel();
        jtfPrecioServicio = new javax.swing.JTextField();
        jlbTipoServicio = new javax.swing.JLabel();
        jbnEditar = new javax.swing.JButton();
        jbnBuscar = new javax.swing.JButton();
        jlbID = new javax.swing.JLabel();
        jtfID = new javax.swing.JTextField();
        jrbMantPreventivo = new javax.swing.JRadioButton();

        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Editar Servicio");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N

        jlbTitulo.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jlbTitulo.setForeground(new java.awt.Color(0, 102, 102));
        jlbTitulo.setText("Editar un servicio");

        jrbMantCorrectivo.setForeground(new java.awt.Color(0, 102, 102));
        jrbMantCorrectivo.setText("Mantenimiento correctivo");

        jbnVolver.setText("Volver");

        jlbDescripcionServicio.setForeground(new java.awt.Color(0, 102, 102));
        jlbDescripcionServicio.setText("Descripcion del servicio");

        jtaDescripcionServicio.setColumns(20);
        jtaDescripcionServicio.setRows(5);
        jScrollPane1.setViewportView(jtaDescripcionServicio);

        jlbPrecioServicio.setForeground(new java.awt.Color(0, 102, 102));
        jlbPrecioServicio.setText("Precio del servicio");

        jlbTipoServicio.setForeground(new java.awt.Color(0, 102, 102));
        jlbTipoServicio.setText("Tipo de servicio");

        jbnEditar.setText("Editar");

        jbnBuscar.setText("Buscar");

        jlbID.setForeground(new java.awt.Color(0, 102, 102));
        jlbID.setText("ID:");

        jrbMantPreventivo.setForeground(new java.awt.Color(0, 102, 102));
        jrbMantPreventivo.setText("Mantenimiento preventivo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbID))
                .addGap(84, 84, 84))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jrbMantPreventivo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jrbMantCorrectivo))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbnBuscar)
                                .addGap(39, 39, 39)
                                .addComponent(jbnEditar)
                                .addGap(38, 38, 38)
                                .addComponent(jbnVolver))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jlbTitulo)))
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(42, 42, 42)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jlbDescripcionServicio)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlbPrecioServicio)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlbTipoServicio)
                                .addGap(6, 6, 6)))
                        .addComponent(jtfPrecioServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(38, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jlbTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                .addComponent(jlbID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbMantPreventivo)
                    .addComponent(jrbMantCorrectivo))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbnEditar)
                    .addComponent(jbnBuscar)
                    .addComponent(jbnVolver))
                .addGap(35, 35, 35))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(36, 36, 36)
                    .addComponent(jlbDescripcionServicio)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jlbPrecioServicio)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jtfPrecioServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jlbTipoServicio)
                    .addContainerGap(113, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbnBuscar;
    private javax.swing.JButton jbnEditar;
    private javax.swing.JButton jbnVolver;
    private javax.swing.JLabel jlbDescripcionServicio;
    private javax.swing.JLabel jlbID;
    private javax.swing.JLabel jlbPrecioServicio;
    private javax.swing.JLabel jlbTipoServicio;
    private javax.swing.JLabel jlbTitulo;
    private javax.swing.JRadioButton jrbMantCorrectivo;
    private javax.swing.JRadioButton jrbMantPreventivo;
    private javax.swing.JTextArea jtaDescripcionServicio;
    private javax.swing.JTextField jtfID;
    private javax.swing.JTextField jtfPrecioServicio;
    // End of variables declaration//GEN-END:variables
}
