/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

/**
 *
 * @author luisf
 */
public class jtfRegisterService extends javax.swing.JInternalFrame {

    /**
     * Creates new form jtfRegisterService
     */
    public jtfRegisterService() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbGroup1 = new javax.swing.ButtonGroup();
        jlbTitulo = new javax.swing.JLabel();
        jlbDescripcionServicio = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaDescripcionServicio = new javax.swing.JTextArea();
        jlbPrecioServicio = new javax.swing.JLabel();
        jtfPrecioServicio = new javax.swing.JTextField();
        jlbTiposServicio = new javax.swing.JLabel();
        jrbMantPreventivo = new javax.swing.JRadioButton();
        jrbMantCorrectivo = new javax.swing.JRadioButton();
        jbnVolver = new javax.swing.JButton();
        jbnRegistrar = new javax.swing.JButton();
        jlbID = new javax.swing.JLabel();
        jtfID = new javax.swing.JTextField();

        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Registrar Servicio");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N

        jlbTitulo.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jlbTitulo.setForeground(new java.awt.Color(0, 102, 102));
        jlbTitulo.setText("Registra un servicio");

        jlbDescripcionServicio.setForeground(new java.awt.Color(0, 102, 102));
        jlbDescripcionServicio.setText("Descripcion del servicio");

        jtaDescripcionServicio.setColumns(20);
        jtaDescripcionServicio.setRows(5);
        jScrollPane1.setViewportView(jtaDescripcionServicio);

        jlbPrecioServicio.setForeground(new java.awt.Color(0, 102, 102));
        jlbPrecioServicio.setText("Precio del servicio");

        jlbTiposServicio.setForeground(new java.awt.Color(0, 102, 102));
        jlbTiposServicio.setText("Tipo de servicio");

        rbGroup1.add(jrbMantPreventivo);
        jrbMantPreventivo.setForeground(new java.awt.Color(0, 102, 102));
        jrbMantPreventivo.setText("Mantenimiento Preventivo");

        rbGroup1.add(jrbMantCorrectivo);
        jrbMantCorrectivo.setForeground(new java.awt.Color(0, 102, 102));
        jrbMantCorrectivo.setText("Mantenimiento correctivo");

        jbnVolver.setText("Volver");

        jbnRegistrar.setText("Registrar");

        jlbID.setForeground(new java.awt.Color(0, 102, 102));
        jlbID.setText("ID:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlbTitulo)
                .addGap(90, 90, 90))
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlbDescripcionServicio)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jrbMantPreventivo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jrbMantCorrectivo))
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jlbPrecioServicio)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jlbTiposServicio)
                                            .addGap(6, 6, 6)))
                                    .addComponent(jtfPrecioServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(69, 69, 69)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlbID))))
                        .addContainerGap(20, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbnRegistrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbnVolver)
                        .addGap(77, 77, 77))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jlbTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbDescripcionServicio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbPrecioServicio)
                    .addComponent(jlbID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfPrecioServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jlbTiposServicio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbMantPreventivo)
                    .addComponent(jrbMantCorrectivo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbnVolver)
                    .addComponent(jbnRegistrar))
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbnRegistrar;
    private javax.swing.JButton jbnVolver;
    private javax.swing.JLabel jlbDescripcionServicio;
    private javax.swing.JLabel jlbID;
    private javax.swing.JLabel jlbPrecioServicio;
    private javax.swing.JLabel jlbTiposServicio;
    private javax.swing.JLabel jlbTitulo;
    private javax.swing.JRadioButton jrbMantCorrectivo;
    private javax.swing.JRadioButton jrbMantPreventivo;
    private javax.swing.JTextArea jtaDescripcionServicio;
    private javax.swing.JTextField jtfID;
    private javax.swing.JTextField jtfPrecioServicio;
    private javax.swing.ButtonGroup rbGroup1;
    // End of variables declaration//GEN-END:variables
}
