/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Beto
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel2 = new javax.swing.JLabel();
        jbnEditar1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuRefacts = new javax.swing.JMenu();
        jMIAddRefacts = new javax.swing.JMenuItem();
        jMIEditRefacts = new javax.swing.JMenuItem();
        jMISearchRefacts = new javax.swing.JMenuItem();
        jMIDeleteRefacts = new javax.swing.JMenuItem();
        jMenuServiceOrder = new javax.swing.JMenu();
        jMIAddOrderService = new javax.swing.JMenuItem();
        jMIEditOrderService = new javax.swing.JMenuItem();
        jMISearchOrderService = new javax.swing.JMenuItem();
        jMIDeleteOrderService = new javax.swing.JMenuItem();
        jMenuServices = new javax.swing.JMenu();
        jMIAddService = new javax.swing.JMenuItem();
        jMIEditService = new javax.swing.JMenuItem();
        jMISearchService = new javax.swing.JMenuItem();
        jMIDeleteService = new javax.swing.JMenuItem();
        jMenuTools = new javax.swing.JMenu();
        jMIAddTool = new javax.swing.JMenuItem();
        jMIEditTool = new javax.swing.JMenuItem();
        jMISearchTool = new javax.swing.JMenuItem();
        jMIDeleteTool = new javax.swing.JMenuItem();
        jMenuClient = new javax.swing.JMenu();
        jMIAddClient = new javax.swing.JMenuItem();
        jMIEditClient = new javax.swing.JMenuItem();
        jMISearchClient = new javax.swing.JMenuItem();
        jMIDeleteClient = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/sstech.png"))); // NOI18N

        jbnEditar1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbnEditar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/log out.png"))); // NOI18N
        jbnEditar1.setText("Salir");
        jbnEditar1.setToolTipText("Salir");

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Menú");

        jDesktopPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jbnEditar1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(343, 343, 343)
                        .addComponent(jbnEditar1))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(355, 355, 355)
                        .addComponent(jLabel1))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(294, 294, 294)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(500, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 629, Short.MAX_VALUE)
                .addComponent(jbnEditar1)
                .addGap(62, 62, 62))
        );

        jMenuRefacts.setBackground(new java.awt.Color(204, 204, 204));
        jMenuRefacts.setForeground(new java.awt.Color(204, 204, 204));
        jMenuRefacts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/refacts.png"))); // NOI18N
        jMenuRefacts.setText("Refacciones");
        jMenuRefacts.setToolTipText("");
        jMenuRefacts.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jMIAddRefacts.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMIAddRefacts.setForeground(new java.awt.Color(0, 102, 102));
        jMIAddRefacts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add.png"))); // NOI18N
        jMIAddRefacts.setText("Registrar");
        jMIAddRefacts.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMIAddRefacts.setFocusPainted(true);
        jMIAddRefacts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIAddRefactsActionPerformed(evt);
            }
        });
        jMenuRefacts.add(jMIAddRefacts);

        jMIEditRefacts.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMIEditRefacts.setForeground(new java.awt.Color(0, 102, 102));
        jMIEditRefacts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edit.png"))); // NOI18N
        jMIEditRefacts.setText("Editar");
        jMenuRefacts.add(jMIEditRefacts);

        jMISearchRefacts.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMISearchRefacts.setForeground(new java.awt.Color(0, 102, 102));
        jMISearchRefacts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search2.png"))); // NOI18N
        jMISearchRefacts.setText("Buscar");
        jMISearchRefacts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMISearchRefactsActionPerformed(evt);
            }
        });
        jMenuRefacts.add(jMISearchRefacts);

        jMIDeleteRefacts.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMIDeleteRefacts.setForeground(new java.awt.Color(0, 102, 102));
        jMIDeleteRefacts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delete.png"))); // NOI18N
        jMIDeleteRefacts.setText("Eliminar");
        jMenuRefacts.add(jMIDeleteRefacts);

        jMenuBar1.add(jMenuRefacts);

        jMenuServiceOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/serviceorder.png"))); // NOI18N
        jMenuServiceOrder.setText("Orden de Servicio");

        jMIAddOrderService.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMIAddOrderService.setForeground(new java.awt.Color(0, 102, 102));
        jMIAddOrderService.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add.png"))); // NOI18N
        jMIAddOrderService.setText("Registrar");
        jMIAddOrderService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIAddOrderServiceActionPerformed(evt);
            }
        });
        jMenuServiceOrder.add(jMIAddOrderService);

        jMIEditOrderService.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMIEditOrderService.setForeground(new java.awt.Color(0, 102, 102));
        jMIEditOrderService.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edit.png"))); // NOI18N
        jMIEditOrderService.setText("Editar");
        jMenuServiceOrder.add(jMIEditOrderService);

        jMISearchOrderService.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMISearchOrderService.setForeground(new java.awt.Color(0, 102, 102));
        jMISearchOrderService.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search2.png"))); // NOI18N
        jMISearchOrderService.setText("Buscar");
        jMenuServiceOrder.add(jMISearchOrderService);

        jMIDeleteOrderService.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMIDeleteOrderService.setForeground(new java.awt.Color(0, 102, 102));
        jMIDeleteOrderService.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delete.png"))); // NOI18N
        jMIDeleteOrderService.setText("Eliminar");
        jMenuServiceOrder.add(jMIDeleteOrderService);

        jMenuBar1.add(jMenuServiceOrder);

        jMenuServices.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/services.png"))); // NOI18N
        jMenuServices.setText("Servicios");

        jMIAddService.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMIAddService.setForeground(new java.awt.Color(0, 102, 102));
        jMIAddService.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add.png"))); // NOI18N
        jMIAddService.setText("Registrar");
        jMIAddService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIAddServiceActionPerformed(evt);
            }
        });
        jMenuServices.add(jMIAddService);

        jMIEditService.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMIEditService.setForeground(new java.awt.Color(0, 102, 102));
        jMIEditService.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edit.png"))); // NOI18N
        jMIEditService.setText("Editar");
        jMenuServices.add(jMIEditService);

        jMISearchService.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMISearchService.setForeground(new java.awt.Color(0, 102, 102));
        jMISearchService.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search2.png"))); // NOI18N
        jMISearchService.setText("Buscar");
        jMenuServices.add(jMISearchService);

        jMIDeleteService.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMIDeleteService.setForeground(new java.awt.Color(0, 102, 102));
        jMIDeleteService.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delete.png"))); // NOI18N
        jMIDeleteService.setText("Eliminar");
        jMenuServices.add(jMIDeleteService);

        jMenuBar1.add(jMenuServices);

        jMenuTools.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tools.png"))); // NOI18N
        jMenuTools.setText("Herramientas");

        jMIAddTool.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMIAddTool.setForeground(new java.awt.Color(0, 102, 102));
        jMIAddTool.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add.png"))); // NOI18N
        jMIAddTool.setText("Registrar");
        jMenuTools.add(jMIAddTool);

        jMIEditTool.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMIEditTool.setForeground(new java.awt.Color(0, 102, 102));
        jMIEditTool.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edit.png"))); // NOI18N
        jMIEditTool.setText("Editar");
        jMenuTools.add(jMIEditTool);

        jMISearchTool.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMISearchTool.setForeground(new java.awt.Color(0, 102, 102));
        jMISearchTool.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search2.png"))); // NOI18N
        jMISearchTool.setText("Buscar");
        jMISearchTool.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMISearchToolActionPerformed(evt);
            }
        });
        jMenuTools.add(jMISearchTool);

        jMIDeleteTool.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMIDeleteTool.setForeground(new java.awt.Color(0, 102, 102));
        jMIDeleteTool.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delete.png"))); // NOI18N
        jMIDeleteTool.setText("Eliminar");
        jMIDeleteTool.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIDeleteToolActionPerformed(evt);
            }
        });
        jMenuTools.add(jMIDeleteTool);

        jMenuBar1.add(jMenuTools);

        jMenuClient.setForeground(new java.awt.Color(204, 204, 204));
        jMenuClient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/client.png"))); // NOI18N
        jMenuClient.setText("Cliente");

        jMIAddClient.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMIAddClient.setForeground(new java.awt.Color(0, 102, 102));
        jMIAddClient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add.png"))); // NOI18N
        jMIAddClient.setText("Registrar");
        jMenuClient.add(jMIAddClient);

        jMIEditClient.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMIEditClient.setForeground(new java.awt.Color(0, 102, 102));
        jMIEditClient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edit.png"))); // NOI18N
        jMIEditClient.setText("Editar");
        jMenuClient.add(jMIEditClient);

        jMISearchClient.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMISearchClient.setForeground(new java.awt.Color(0, 102, 102));
        jMISearchClient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search2.png"))); // NOI18N
        jMISearchClient.setText("Buscar");
        jMenuClient.add(jMISearchClient);

        jMIDeleteClient.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMIDeleteClient.setForeground(new java.awt.Color(0, 102, 102));
        jMIDeleteClient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delete.png"))); // NOI18N
        jMIDeleteClient.setText("Eliminar");
        jMenuClient.add(jMIDeleteClient);

        jMenuBar1.add(jMenuClient);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMIAddRefactsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIAddRefactsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMIAddRefactsActionPerformed

    private void jMISearchRefactsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMISearchRefactsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMISearchRefactsActionPerformed

    private void jMIAddOrderServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIAddOrderServiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMIAddOrderServiceActionPerformed

    private void jMIAddServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIAddServiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMIAddServiceActionPerformed

    private void jMIDeleteToolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIDeleteToolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMIDeleteToolActionPerformed

    private void jMISearchToolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMISearchToolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMISearchToolActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuItem jMIAddClient;
    private javax.swing.JMenuItem jMIAddOrderService;
    private javax.swing.JMenuItem jMIAddRefacts;
    private javax.swing.JMenuItem jMIAddService;
    private javax.swing.JMenuItem jMIAddTool;
    private javax.swing.JMenuItem jMIDeleteClient;
    private javax.swing.JMenuItem jMIDeleteOrderService;
    private javax.swing.JMenuItem jMIDeleteRefacts;
    private javax.swing.JMenuItem jMIDeleteService;
    private javax.swing.JMenuItem jMIDeleteTool;
    private javax.swing.JMenuItem jMIEditClient;
    private javax.swing.JMenuItem jMIEditOrderService;
    private javax.swing.JMenuItem jMIEditRefacts;
    private javax.swing.JMenuItem jMIEditService;
    private javax.swing.JMenuItem jMIEditTool;
    private javax.swing.JMenuItem jMISearchClient;
    private javax.swing.JMenuItem jMISearchOrderService;
    private javax.swing.JMenuItem jMISearchRefacts;
    private javax.swing.JMenuItem jMISearchService;
    private javax.swing.JMenuItem jMISearchTool;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuClient;
    private javax.swing.JMenu jMenuRefacts;
    private javax.swing.JMenu jMenuServiceOrder;
    private javax.swing.JMenu jMenuServices;
    private javax.swing.JMenu jMenuTools;
    private javax.swing.JButton jbnEditar1;
    // End of variables declaration//GEN-END:variables
}
