package view;

import controller.ServiceOrder_stack;
import model.ServiceOrder;

/**
 *
 * @author nerif
 */
public class ServiceOrder_Register_Edit extends javax.swing.JInternalFrame {

    /**
     * Creates new form ServiceOrder_Register
     */
    Menu main;
    ServiceOrder_stack soStack;
    
    public ServiceOrder_Register_Edit(Menu window, ServiceOrder_stack soStk) {
        initComponents();
        main = window;
        soStack = soStk;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngEstado = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        rbtnProceso = new javax.swing.JRadioButton();
        lblCelular1 = new javax.swing.JLabel();
        lblEstado1 = new javax.swing.JLabel();
        txtCliente = new javax.swing.JTextField();
        lblFechaSalida1 = new javax.swing.JLabel();
        txtNCelular = new javax.swing.JTextField();
        lblPedido1 = new javax.swing.JLabel();
        txtNPedido = new javax.swing.JTextField();
        txtFSalida = new javax.swing.JTextField();
        rbtnEspera = new javax.swing.JRadioButton();
        lblFechaEntrega1 = new javax.swing.JLabel();
        jlbTitulo1 = new javax.swing.JLabel();
        txtFEntrega = new javax.swing.JTextField();
        lblCliente1 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Registrar - Orden de Servicio");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        rbtnProceso.setBackground(new java.awt.Color(0, 102, 102));
        btngEstado.add(rbtnProceso);
        rbtnProceso.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        rbtnProceso.setForeground(new java.awt.Color(204, 204, 204));
        rbtnProceso.setText("En proceso");
        rbtnProceso.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rbtnProceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnProcesoActionPerformed(evt);
            }
        });

        lblCelular1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblCelular1.setForeground(new java.awt.Color(255, 255, 255));
        lblCelular1.setText("Número de celular:");

        lblEstado1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblEstado1.setForeground(new java.awt.Color(255, 255, 255));
        lblEstado1.setText("Estado:");

        txtCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClienteActionPerformed(evt);
            }
        });

        lblFechaSalida1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblFechaSalida1.setForeground(new java.awt.Color(255, 255, 255));
        lblFechaSalida1.setText("Fecha de pedido:");

        lblPedido1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblPedido1.setForeground(new java.awt.Color(255, 255, 255));
        lblPedido1.setText("Número de pedido:");

        rbtnEspera.setBackground(new java.awt.Color(0, 102, 102));
        btngEstado.add(rbtnEspera);
        rbtnEspera.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        rbtnEspera.setForeground(new java.awt.Color(204, 204, 204));
        rbtnEspera.setText("En espera");
        rbtnEspera.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblFechaEntrega1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblFechaEntrega1.setForeground(new java.awt.Color(255, 255, 255));
        lblFechaEntrega1.setText("Fecha de entrega:");

        jlbTitulo1.setBackground(new java.awt.Color(255, 255, 255));
        jlbTitulo1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jlbTitulo1.setForeground(new java.awt.Color(255, 255, 255));
        jlbTitulo1.setText("Registrar / Editar Orden de Servicio");

        lblCliente1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblCliente1.setForeground(new java.awt.Color(255, 255, 255));
        lblCliente1.setText("Cliente:");

        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(0, 102, 102));
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add.png"))); // NOI18N
        btnAdd.setToolTipText("Añadir");
        btnAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnEdit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(0, 102, 102));
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edit.png"))); // NOI18N
        btnEdit.setToolTipText("Editar");
        btnEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(0, 102, 102));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/back.png"))); // NOI18N
        btnBack.setToolTipText("Regresar");
        btnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlbTitulo1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lblCelular1)
                            .addGap(18, 18, 18)
                            .addComponent(txtNCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lblCliente1)
                            .addGap(18, 18, 18)
                            .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lblEstado1)
                            .addGap(18, 18, 18)
                            .addComponent(rbtnEspera)
                            .addGap(18, 18, 18)
                            .addComponent(rbtnProceso))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lblFechaSalida1)
                            .addGap(18, 18, 18)
                            .addComponent(txtFSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lblPedido1)
                            .addGap(18, 18, 18)
                            .addComponent(txtNPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblFechaEntrega1)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(70, 70, 70)
                                    .addComponent(btnAdd)))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(9, 9, 9)
                                    .addComponent(btnEdit)
                                    .addGap(41, 41, 41)
                                    .addComponent(btnBack))
                                .addComponent(txtFEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbTitulo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPedido1)
                    .addComponent(txtNPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCliente1)
                    .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCelular1)
                    .addComponent(txtNCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEstado1)
                    .addComponent(rbtnEspera)
                    .addComponent(rbtnProceso))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaSalida1)
                    .addComponent(txtFSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaEntrega1)
                    .addComponent(txtFEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnAdd, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnBack))
                    .addComponent(btnEdit))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtnProcesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnProcesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnProcesoActionPerformed

    private void txtClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClienteActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        String ordernum = txtNPedido.getText();
        String client = txtCliente.getText();
        String phone = txtNCelular.getText();
        String dBegin = txtFSalida.getText();
        String dEnd = txtFEntrega.getText();
        int state = 0;
        
        if (rbtnEspera.isSelected()) {
            state = 1;
        }
        if (rbtnProceso.isSelected()) {
            state = 2;
        }
        
        soStack.add_SO(ordernum, client, phone, state, dBegin, dEnd, "", 0, 0, 0);
        
        txtNPedido.setText("");
        txtCliente.setText("");
        txtNCelular.setText("");
        txtFSalida.setText("");
        txtFEntrega.setText("");
        rbtnEspera.setSelected(false);
        rbtnProceso.setSelected(false);
        txtNPedido.requestFocus();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        String search = txtNPedido.getText();
        String client = txtCliente.getText();
        String phone = txtNCelular.getText();
        String dBegin = txtFSalida.getText();
        String dEnd = txtFEntrega.getText();
        int state = 0;
        
        if (rbtnEspera.isSelected()) {
            state = 1;
        }
        if (rbtnProceso.isSelected()) {
            state = 2;
        }
        
        soStack.edit_SO(search, client, phone, state, dBegin, dEnd);
        
        txtNPedido.setText("");
        txtCliente.setText("");
        txtNCelular.setText("");
        txtFSalida.setText("");
        txtFEntrega.setText("");
        rbtnEspera.setSelected(false);
        rbtnProceso.setSelected(false);
        txtNPedido.requestFocus();
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        //Si se presiona, cerrara la ventana
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnEdit;
    private javax.swing.ButtonGroup btngEstado;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlbTitulo1;
    private javax.swing.JLabel lblCelular1;
    private javax.swing.JLabel lblCliente1;
    private javax.swing.JLabel lblEstado1;
    private javax.swing.JLabel lblFechaEntrega1;
    private javax.swing.JLabel lblFechaSalida1;
    private javax.swing.JLabel lblPedido1;
    private javax.swing.JRadioButton rbtnEspera;
    private javax.swing.JRadioButton rbtnProceso;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtFEntrega;
    private javax.swing.JTextField txtFSalida;
    private javax.swing.JTextField txtNCelular;
    private javax.swing.JTextField txtNPedido;
    // End of variables declaration//GEN-END:variables
}
